server:
  port: 6669
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/netty?characterEncoding=UTF-8&useUnicode=true&serverTimezone=GMT%2B8
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mybatis/*.xml
